<?php 

/**
 * Provides general Art functionality for Student Art World site
 * Package: Student Art World (SAW) module
 *
 * Developers:
 *  Rafal Wieczorek <rafal.wieczorek@itv.com>
 *
 */

function saw_art_form_alter (&$form, $form_state, $form_id)
{
  if ($form_id == 'art_node_form')
  {
    drupal_add_js (drupal_get_path ('module', 'saw_art') . "/node_edit_type_art.js", "saw_art");
    
    $form ['#validate'][] = 'saw_art_form_validate';
  }
}

function saw_art_form_validate (&$form, $form_state)
{
  drupal_add_js (drupal_get_path ('module', 'saw_art') . "/node_edit_type_art.js", "saw_art");
}