<?php
// $Id: modr8_bypass.module,v 1.3 2010/04/05 14:52:00 johngriffin Exp $
/**
 * @file
 * Modr8 Bypass permits selected roles to bypass node moderation
 */


/**
 * Implementation of hook_menu().
 */
function modr8_bypass_menu() {
  $items = array();
  $items['admin/settings/modr8/bypass'] = array(
    'title'             => 'Modr8 Bypass',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('modr8_bypass_settings'),
    'access callback'   => 'user_access',
    'access arguments'  => array('administer site configuration'),
    'type'              => MENU_LOCAL_TASK,
    'weight'            => 1,
  );
  return $items;
}

/**
 * Change the URL of the modr8 settings page so we can add a tab to it.
 */
function modr8_bypass_menu_alter(&$items) {
  $items['admin/settings/modr8/general'] = $items['admin/settings/modr8'];
  $items['admin/settings/modr8/general']['type'] = MENU_DEFAULT_LOCAL_TASK;
  $items['admin/settings/modr8/general']['weight'] = -2;
  $items['admin/settings/modr8']['weight'] = 0;
}

/**
 * Configuration form
 */
function modr8_bypass_settings() {
  $form['modr8_bypass_publish'] = array(
    '#type' => 'checkbox',
    '#title' => t('Set bypassed node types to be published by default'),
    '#description' => t('Setting this option will override the default workflow settings for nodes types which have been set to be bypassed.'),
    '#default_value' => variable_get('modr8_bypass_publish', FALSE),
  );
  $form['modr8_bypass_suppress'] = array(
    '#type' => 'checkbox',
    '#title' => t('Remove moderate checkbox for bypassed node types'),
    '#description' => t('Setting this option will remove the "In Moderation Queue" checkbox for users who have permission to bypass moderation.'),
    '#default_value' => variable_get('modr8_bypass_suppress', FALSE),
  );
  return system_settings_form($form);
}

/**
 * Implementation of hook_perm().
 */
function modr8_bypass_perm() {
  $perms = array();
  foreach (node_get_types() as $type) {
      $name = check_plain($type->type);
      $node_options = variable_get('node_options_'. $name, array('status', 'promote'));
      if (in_array('moderate', $node_options)) {
        $perms[] = 'bypass '. $name .' moderation';
      }
  }
  return $perms;
}

/**
 * Implementation of hook_nodeapi().
 *
 * Set the moderation state of a node.
 */
function modr8_bypass_nodeapi(&$node, $op, $teaser = NULL, $page = NULL) {
  switch ($op) {
    case 'prepare':
      if (user_access('bypass '. $node->type .' moderation')) {
        $node->moderate = 0; // set the node to not be moderated.
      }
    break;
  }
}

/**
 * Implementation of hook_nodeapi().
 *
 * If the requisite options are set then remove the moderation checkbox 
 * and set published as default on node add forms
 */
function modr8_bypass_form_alter(&$form, $form_state, $form_id) {
  if (isset($form['type']['#value']) && $form['type']['#value'] .'_node_form' == $form_id)  {
    
    // If requisite option is set then remove the moderate checkbox
    if (user_access('bypass '. $form['type']['#value'] .' moderation')
      &&  variable_get('modr8_bypass_suppress', FALSE)) {
      if (user_access('administer nodes')) {
        unset($form['options']['moderate']);
      }
      elseif (user_access('moderate content')) {
        unset($form['moderate']);
      }
      
      // If requisite option is set then set the node to be published by default
      if (variable_get('modr8_bypass_publish', FALSE)) {
        $form['options']['status']['#default_value'] = 1;
      }
    }
  }
}
