<?php
// $Id: mp_file.install,v 1.1.2.4 2010/01/01 00:59:37 syndicatestorm Exp $

/**
 * @file
 * Database installation, uninstallation, and updates for the mp_file marketplace module.
 */

/**
 * Implements hook_uninstall()
 */
function  mp_file_uninstall() {
  variable_del('mp_file_show_feature_list');
  variable_del('mp_file_show_commit_checkbox');
  variable_del('mp_file_require_upload');
  variable_del('mp_file_replace_feature_on_upload');
}